### PR TITLE
Modeling admin

### PR DESCRIPTION
**Pull request by pieroblunda**

### CODE REVIEW

**Comment by lirantal** [comment]
@pieroblunda  ?
no comments? no description?

The generator-meanjs project is also not really maintained much anymore.
How about you discuss this PR with us on the meanjs/mean repo?

**Comment by pieroblunda** [comment]
I am so sorry. I wos confused. Thanks you for notice me.

**Comment by dalelotts** [comment]
>The generator-meanjs project is also not really maintained much anymore.

What?  Why isn't it noted as deprecated?

**Comment by lirantal** [comment]
@dalelotts not deprecated. There's a difference.
The meanjs generator works just fine, but it works with version 0.3.3 which is the previous stable version. The current mean.js version is 0.4 and there's no meanjs generator version for it, yet. If someone is willing to work on it we'll gladly welcome it.

**Pull request closed without merging**
