### PR TITLE
Bump to Version 0.4.3

### PR DESCRIPTION
**Pull request by codydaig**
@ilanbiala I think it's time for the next release! 

@UndeadBaneGitHub Thanks for all the contributions in this Release!! Tagging you here to confirm that the project is ready to release the next version.

### CODE REVIEW

**Comment by UndeadBaneGitHub** [comment]
@codydaig thanks! I will update the last PR from me (MEAN module) today a bit later, so that it would be ready for the release as well

**Comment by ilanbiala** [comment]
Yeah I'm gonna just wait for the module one, then I'll release.

**Comment by codydaig** [comment]
@ilanbiala I think this is ready to release now!! :-D

**Comment by ilanbiala** [comment]
#186 actually, and then I am publishing a new release.

**Comment by codydaig** [comment]
@ilanbiala Okay. I want to get a set of eyes on that PR from a windows user before I say merge, but hopefully by tonight we should be good.

**Comment by ilanbiala** [comment]
:+1:

**Comment by UndeadBaneGitHub** [comment]
Please, see https://github.com/meanjs/generator-meanjs/pull/190 as it fixes 4 latest open issues. Should be a good PR for the version.

**Comment by cataquil** [comment]
will we get crud-generator ?

**Comment by UndeadBaneGitHub** [comment]
@cataquil Yep, working on it! Also, templates will get updated to the latest version!

**Pull request merged**
