### PR TITLE
release: 0.4.2

### PR DESCRIPTION
**Pull request by codydaig**

### CODE REVIEW

**Comment by codydaig** [comment]
@ilanbiala Ready for release. The current code base has tons of bug fixes that need too get published ASAP. I am working on teste but don't think it should hold up the release since this code base has been tested on various sfstemo ever the past 2 months waiting for my PR too get merged.

**Comment by lirantal** [comment]
LGTM, let's roll it out in the next week to be in sync with the main repo.

**Comment by mleanos** [comment]
LGTM

**Comment by codydaig** [comment]
@ilanbiala Ready to publish! :-D

**Comment by codydaig** [comment]
@ilanbiala Fixed 1 bug fix and wrote some tests it #150

**Comment by ilanbiala** [comment]
@codydaig awesome, what was the bug fix?

**Pull request merged**
