### PR TITLE
Angular , Express and CRUD subgenerator with unit tests

### PR DESCRIPTION
**Pull request by keithics**
Based on 0.4-dev
Let me know your thoughts on my PR. Thank you.

screen shot 2015-12-24 at 6 13 13 am

### CODE REVIEW

**Comment by UndeadBaneGitHub** [comment]
@keithics Ehm... Isn't it pretty much exactly the same as the first version of subgenerators that have been PRed already and are almost merged?..

**Comment by keithics** [comment]
@UndeadBaneGitHub I based it on 0.4-dev.. and fixes all of the bugs and depreciated dependencies to work with the latest yeoman. Also added all of the unit tests.

**Comment by UndeadBaneGitHub** [comment]
@keithics I see. I looked through the code you've submitted, and it seems to me, that you mostly ported the old generators - just like I did before.
The thing is, we've already introduced some changes to logics of subgenerators for 0.4.2 that I've PRed, so I suppose, these changes should also be added to your code as well.

I'm now finishing updating each generator with these changes, will be done shortly.

**Comment by keithics** [comment]
@UndeadBaneGitHub  oh ;) I wish you luck on finishing it. ill close my PR. thank you.

**Comment by UndeadBaneGitHub** [comment]
@keithics Don't rush it! :)
I omitted CRUD generator for now - wanted all more simple ones to get proper first. Would be really cool, if you could PR it, I think, especially as you've implemented it already.

**Comment by keithics** [comment]
@UndeadBaneGitHub okay, will do. I'll create another branch just for crud module.

**Comment by UndeadBaneGitHub** [comment]
@keithics Cool! You can use any `express-route` PR as an example of changes introduced (mainly, moving name from argument to prompt + some more minor ones) - we've come to an agreement on it.

**Comment by keithics** [comment]
@UndeadBaneGitHub okay, will take a look at it now. :+1:

**Pull request closed without merging**
