### PR TITLE
confirm before delete.

### PR DESCRIPTION
**Pull request by kuldipem**
I have added to  confrim() before remove on view, so user do not remove by mistake.

### CODE REVIEW

**Comment by kuldipem** [comment]
Controller should be thin as possible.

**Comment by NeverOddOrEven** [comment]
view should not encode any logic, still not at all comfortable with the use of "onclick".

**Comment by NeverOddOrEven** [comment]
Per https://github.com/meanjs/mean/pull/275#issuecomment-69386516, this needs refactoring before it can be accepted.

**Comment by kuldipem** [comment]
@NeverOddOrEven , I have just updated  ```onclick``` => ```ng-click```, is it ok ?

**Comment by auterium** [comment]
I agree with @NeverOddOrEven, the confirm should be triggered from the remove() function (within the controller) and not from the view. Also, as noted on other comments, using plain confirm is uggly, and since Angular-UI is already present in the generator, it should use a modal to do the confirmation.

I hate just making the comment and not creating an actual pull-request, but I've just discovered MEAN.JS today and still not sure how to use this branch to try it and [hack] enhace it.

**Comment by kuldipem** [comment]
@auterium, I am closing this PR in favor of #82. Nice work @auterium .

**Pull request closed without merging**
