### PR TITLE
Bump to 0.4.5

### PR DESCRIPTION
**Pull request by codydaig**
Fixes eslint errors.

This bump will need to get merged and published, but I do not have permission to publish new versions on npm.

### CODE REVIEW

**Comment by lirantal** [comment]
@codydaig let me know what needs to be done and I'll push it.

**Comment by codydaig** [comment]
@lirantal #238 is my PR for trying to get travis fixed. I'm not sure what happened but it looks like we're missing the g++ compiler settings. I'll tag you in that PR when it's passing and ready to be merged. Let me know if you have any other insights on that as well on why it might be failing.

**Comment by lirantal** [comment]
Got it, thanks.

**Comment by lirantal** [comment]
g++ doesn't seem to be enough, or this is actually related to npm itself?

**Comment by ilanbiala** [comment]
I'll follow up with the new version and publish it once we fix the issues. Let me get up to speed on all the changes and CI issues.

**Comment by codydaig** [comment]
Rebased, and waiting for tests to pass.

**Comment by ilanbiala** [comment]
@codydaig what about the 2 PRs that were closed? Do we not need them anymore? Also, shouldn't we update the Travis CI config to be in line with the main repo's node versions?

**Comment by codydaig** [comment]
@ilanbiala I only opened those as attempts to fix the builds and I believe they were duplicates. Feel free to reopen the latest one if you want it to match the meanjs repo

**Comment by lirantal** [comment]
@ilanbiala you're taking care of pushing the fixes here to npm when ready?

**Comment by ilanbiala** [comment]
Yes, but I want to get in 1 of the PRs that is ready, but just needs to be squashed.

**Comment by codydaig** [comment]
@ilanbiala When your ready, go ahead and merge this and release. Thanks!

**Comment by ilanbiala** [comment]
@codydaig sorry I'm a little late, just got back from vacation, merging and publishing.

**Comment by codydaig** [comment]
@ilanbiala No worries! I'm working full time and a full time student, so my availability is limited.

**Pull request merged**
