### PR TITLE
Test infrastructure

### LINKED ISSUE #172: Add more tests and test infrastructure
@codydaig I'd like to add Gulp here to add some extra testing, such as running JSHint+ESLint in addition to Mocha. Any objections?

### PR DESCRIPTION
**Pull request by ilanbiala**
WIP
Fixes #172

### CODE REVIEW

**Comment by ilanbiala** [comment]
@codydaig tests are passing, but does that guarantee the JSHint and ESLint are actually running?

Once everything is finalized and reviewed, I'll squash and rebase.

**Comment by mleanos** [comment]
LGTM

**Comment by ilanbiala** [comment]
@codydaig if LGTY as well, I'll squash and merge.

**Comment by codydaig** [comment]
@ilanbiala Sorry for the delay. Traveling this week. It looks as though they are passing. 

LGTM

**Comment by UndeadBaneGitHub** [comment]
@ilanbiala This one does not solve timeouts problem. I have removed `this.timeout(0)` in all the tests - and they started to fail whenever `git pull` is involved, as it takes quite some time from where I am.

I am currently trying to find a solution for this problem

**Pull request merged**
