### PR TITLE
Old generators have been refactored to use new structure

### PR DESCRIPTION
**Pull request by UndeadBaneGitHub**
With tests

TODO:
- Add CRUD generator
- Add server ACL generator (kinda wonder, how to make one yet)

### CODE REVIEW

**Comment by codydaig** [comment]
@UndeadBaneGitHub Awesome! I would prefer each sub generator to be it's own PR to make review / discussions easier to track, and some can get merged in faster than others if there's more work to be done. As you break them up, We'll do a detailed review and they should be able to get merged in! Thanks a bunch!

**Comment by UndeadBaneGitHub** [comment]
@codydaig sure, I will break the up shortly and do incremental PRs. 
Would you like me to split the tests into different files as well - or rather just add them one by one to angular.test.js/express.test.js?

**Comment by codydaig** [comment]
@UndeadBaneGitHub I'd prefer separate files as well. 

Thanks again!

**Comment by codydaig** [comment]
@UndeadBaneGitHub A couple style things I notice right now to avoid a huge stream of line comments from reviewers:
- There should be a new line at the end of each file.
- Indentations should be 2 spaces.
- 'use strict' should be at the top of each file.

**Comment by UndeadBaneGitHub** [comment]
@codydaig thanks for that, will address it in the code as I add PRs :)

**Comment by UndeadBaneGitHub** [comment]
@codydaig Added separate PRs for each of the features separately and changed the code style.
I can also add .idea folder to the project, so that if anyone would use Webstorm (like I do) would have proper settings in addition to .editorconfig, which Webstorm for some reason ignored.

**Pull request closed without merging**
