### PR TITLE
Fix undefined log output

### PR DESCRIPTION
**Pull request by ilanbiala**

### CODE REVIEW

**Comment by ilanbiala** [comment]
@codydaig this should be pretty simple. I also want to merge this in for 0.4.2, so if LGTY, then I'll reword the commit and merge along with #152 and then release.

**Comment by codydaig** [comment]
Does this log undefined when you run the generator or just in the tests?

**Comment by ilanbiala** [comment]
This removes the undefined log in both cases.

**Comment by codydaig** [comment]
LGTM

Any idea when this.yeoman stopped working? It was working when I first started working on this project.

**Comment by ilanbiala** [comment]
Not sure, maybe when yeoman was updated from 0.18 to 0.20?

**Comment by codydaig** [comment]
Oh well, go ahead and merge and publish! :-D

**Pull request merged**
