### PR TITLE
[bug] Match PR 921 from meanjs/mean

### PR DESCRIPTION
**Pull request by codydaig**

### CODE REVIEW

**Comment by ilanbiala** [comment]
@codydaig instead of having to upkeep the master, can't we just write code to regex replace what we want and directly use the master code? It would be simpler I think, no?

**Comment by codydaig** [comment]
@ilanbiala I'll look into that this week. Do we want to merge this in for now until we figure out a better solution?

**Comment by ilanbiala** [comment]
@codydaig Let's start a gist to work on it, I'd prefer not to merge this in. Want to work on it here? https://gist.github.com/ilanbiala/cf2182f50057a6bc46ad

**Comment by codydaig** [comment]
@ilanbiala My issue with not merging it in is that the generator breaks on the current master branch until this gets merged in.

**Comment by ilanbiala** [comment]
@codydaig merged, but let's continue discussion here.

**Comment by codydaig** [comment]
@ilanbiala SGTM. Instead of a regex, what about just reading the json file and parsing it as json. Modify the object for what we need to and then stringify it and save it back to the file?

**Comment by ilanbiala** [comment]
@codydaig that's also fine.

**Pull request merged**
