### PR TITLE
Add support for non rm -rf supported command prompts

### PR DESCRIPTION
**Pull request by ilanbiala**
@codydaig 
Windows in particular, should finally resolve https://github.com/meanjs/generator-meanjs/issues/118

### CODE REVIEW

**Comment by codydaig** [comment]
@mleanos Can you give this a shot on Windows? Thanks!

**Comment by UndeadBaneGitHub** [comment]
Testing that on Windows right now. I actually suggest adding additional assertions `assert.noFile` to the tests to be absolutely sure the folders are properly deleted.

**Comment by codydaig** [comment]
@UndeadBaneGitHub I'd love to get additional test coverage. However, I think that should be a separate PR. Let us know how it does on windows!

**Comment by UndeadBaneGitHub** [comment]
@codydaig @ilanbiala Looks ok on my Windows 10.
However, my tests, checking contents of the files for routes fail. I strongly suspect, it is because I use `\n` as a newline character, and for Windows it is `\r\n`. But that's a completely different story, and I will address it in "fix timeout(0), temp folder and stuff" PR that's coming today later in the evening.

**Comment by ilanbiala** [comment]
@UndeadBaneGitHub try using https://nodejs.org/dist/latest-v4.x/docs/api/os.html#os_os_eol to get it working independent of OS.

**Comment by UndeadBaneGitHub** [comment]
@ilanbiala Yep, I will add them there too

**Pull request merged**
