### PR TITLE
Remove eslint error on crud-module generated files

### PR DESCRIPTION
**Pull request by feroj21**
Hi There, I created a crud-module with generator-meanjs and run `docker run`, But it showing error and exited. It took 2 hours to find the error. Finally I saw its about eslint task. It will be good if you see the changes and merge if you think its necessary.

### CODE REVIEW

**Comment by ilanbiala** [comment]
LGTM. @codydaig LGTY?

**Comment by water42** [comment]
Personally I think you should stick close to John Papa's guide for consistency, but the entire main repository would have to be refactored as well

**Comment by codydaig** [comment]
Unless I'm seeing things funky, the code changed in this PR currently uses John Papa's style guide and this PR changes it to the other way.

**Comment by water42** [comment]
I think you might be seeing things funky.

John Papa's guide uses the wrap-iife inside option: ` })();` and this PR changes the generator to be consistent with the wrap-iife outside option: `}());` used by the main meanjs repository (which is specified in the .eslintrc, hence causing errors when it was John Papa's way). It seems that the eslint default is "outside" anyways: http://eslint.org/docs/rules/wrap-iife

**Comment by codydaig** [comment]
Ah. I get what your saying now. 

@ilanbiala LGTM

**Comment by Valonix** [comment]
So,  will you  merge PR?

**Pull request merged**
