### PR TITLE
Update to match PR 878 in meanjs/mean

### PR DESCRIPTION
**Pull request by codydaig**
Update the package.json and bower.json to match the latest meanjs/mean repo since #878 has been merged in.

### CODE REVIEW

**Comment by lirantal** [comment]
@codydaig why do we have to keep up with those files manually all the time?

**Comment by lirantal** [comment]
BTW your PR shows that it's merging into meanjs/master, can you re-check that?

**Comment by codydaig** [comment]
@lirantal There is only 3 files that we need to keep up with currently because we customize it for the user by putting their app name  in there. Package.json, bower.json, and config/env/default.js

**Comment by codydaig** [comment]
and its merging into the master branch of the generator-meanjs repo in the meanjs organization.

**Comment by ilanbiala** [comment]
@codydaig not sure if everyone feels the same way, but I still prefer using `~` for versioning rather than `^` because some people just aren't that good about being careful.

**Comment by codydaig** [comment]
@ilanbiala This was copied directly from the main repo, and I think it needs to be consistent between the two.

**Comment by ilanbiala** [comment]
@codydaig I completely agree, I was planning on switching the generator repo all to `~` if no one has an issue, and once we update deps switch it over in the framework repo. Objections?

**Comment by mleanos** [comment]
:+1: On using `~` Upgrading libraries should be intentional.

**Comment by codydaig** [comment]
If there's proposed changes, I would rather see them get made and discussed in the main repo before brought over here since that's where the bulk of the community and testing is. I'm skeptical on having differences between the two for debugging and bug assistance.

**Comment by ilanbiala** [comment]
@codydaig agreed, but updating everything in the framework will be quite intensive.

**Comment by codydaig** [comment]
@ilanbiala For the package.json for the generator it's self I'm on board with `~`, however, that doesn't affect this PR. This PR is adjusting the package.json and bower.json that's generated to match the package.json and bower.json in the framework.

**Comment by ilanbiala** [comment]
@codydaig this PR is for the json files that are templates for the generator, right?

**Comment by codydaig** [comment]
@ilanbiala This PR is for the json files that are templates for when the framework is generated. It disregards the json files when the project is cloned, and replaces them with these.

**Comment by codydaig** [comment]
@ilanbiala Can we get this merged in? The master branch selection is broken until this gets merged in.

**Comment by lirantal** [comment]
@codydaig yeah sorry about that, I got confused with the meanjs `master` branch.

**Comment by codydaig** [comment]
@lirantal No worries.

**Pull request merged**
