### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Brianmanden**
Fixed minor grammatical error.

### CODE REVIEW

**Comment by Brianmanden** [comment]
:+1: 

Keep up the good work boys

**Comment by lirantal** [comment]
@Brianmanden closed because...?

**Comment by Brianmanden** [comment]
Ohh.. I am new to this GitHub thing. I thought I could close it after I had submitted the correction.

**Comment by lirantal** [comment]
@ilanbiala pretty straightforward this one. LGTY?

**Comment by Brianmanden** [comment]
Yep. It´s fine :)

**Comment by lirantal** [comment]
@Brianmanden stop closing, we need to merge this pull request.

**Comment by codydaig** [comment]
@Brianmanden The generator now relies on the main repo for changes like this. If this still needs to be updated with the latest version, can you submit your PR over there github.com/meanjs/mean?

Thanks!

@ilanbiala This can be closed.

**Pull request closed without merging**
