### PR TITLE
bug

### PR DESCRIPTION
**Pull request by Asamaha**
"express": "^4.13.1",
      "express-session": "^1.11.3",
      "forever": "~0.14.2",
 +    "generate-password": "^1.1.1",
      "glob": "^5.0.13",
      "grunt": "0.4.5",
      "grunt-cli": "~0.1.13",

### CODE REVIEW

**Comment by ilanbiala** [comment]
Where do you see a "testing" directory? Ours is called "test".

**Comment by codydaig** [comment]
@Asamaha Can you elaborate a bit on where the "testing" directory is coming from?

**Comment by Asamaha** [comment]
Here is where it comes from $ yo meanjs:express-test <model-name>.

**Comment by ilanbiala** [comment]
Closing since no response. @Asamaha if you figure out where that directory comes from, feel free to reply and we'll reopen.

**Pull request closed without merging**
